### ISSUE TITLE
The sudoku has more than one solution

### ISSUE THREAD

**Issue by FliegendeWurst** [xiegeo/commit-sudoku#35]
I'm not sure that this is really a problem, but I thought it would be important to mention.

**Comment by xiegeo** [comment]
This is not a problem. If you go back to history you can see that I started with just a number. Many other numbers got filled in without prior coordination, so there is no way for anyone to have know what the eventual solution will be. Thank you for asking this question, as the process of how existing number was put there may not be obvious to everyone. Basically, we are not just solving the puzzle, but also making it.

As more numbers get filled in, the solution space become smaller, which makes putting in new numbers harder. The game becoming harder as we play it makes it interesting for myself but also makes it harder for new comers.

The game have gotten to the point where it looks like a traditional Sudoku puzzle, but can not be solved like one. Traditional Sudoku puzzles have only one solution which you can reason in steps by proving a cell must contain a number. Our puzzle was not created like that, and having easy answers quickly filled so unknown cells appear to be able to take multiple solutions, this make knowing for sure which number to use much more difficult. 

My suggestion is that you don't have to prove anything to fill in a number. You can simply fill in any number of any cell that is not obviously wrong. We can however discuss strategy to use to make good guesses.

**Comment by rain-1** [comment]
it now has a unique solution.

**Comment by BlueLightning42** [comment]
lol
